### PR TITLE
template: Add Dependabot GH Actions updater

### PR DESCRIPTION
**Pull request by olleolleolle**
This was inspired by alexwayfer's comment about version management of Actions.

A link was offered:
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

This change adds Dependabot configuration "keep GitHub Actions updated" to all repositories which use this template.

The benefit is that some small maintenance is automated.

### CODE REVIEW

**Review by iMacTia — APPROVED** [review]
This is really cool! Thank you @olleolleolle

**Comment by AlexWayfer** [comment]
Why separated workflow? I'm not an expert in this.

**Comment by AlexWayfer** [comment]
Also, probably you want something similar for this repo (at the root), don't you?

**Comment by olleolleolle** [comment]
Yes, we do want that.

This is separate from Workflows - this is outside that directory. This is a config file for Dependabot.

**Comment by AlexWayfer** [comment]
> This is separate from Workflows - this is outside that directory. This is a config file for Dependabot.

I've read the documentation and now I got it. Weird, but OK, thank you.

**Pull request merged**
