### PR TITLE
Fix CI fails

### PR DESCRIPTION
**Pull request by AlexWayfer**
GitHub Setup Ruby Action doesn't recognize Gemfile groups.

Also generate template via bundled `gem_generator` version.

Also update it.

### CODE REVIEW

**Comment by olleolleolle** [comment]
Thanks for the fix!

**Comment by AlexWayfer** [comment]
Phew, now it seems OK and ready.

Was not too obvious what's wrong, but fortunately I had similar experience with another generator and its specs a long time ago.

**Review by olleolleolle — APPROVED** [review]
Looks good and passes specs!

**Comment by olleolleolle** [comment]
Thanks, @AlexWayfer , for your good recall and diligent fixes!

**Pull request merged**
